"""
Dateirolle:
Diese Migration erweitert das Schema um die Stuecklistenpositionen, damit
Fertigprodukte mit benoetigten Komponenten verknuepft werden koennen.
Generated by Django 6.0.3 on 2026-03-10 22:57
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Zweck:
    Beschreibt die Schemaaenderung zur Einfuehrung des Modells `BillOfMaterialItem`.
    Parameter:
    Keine Methodenparameter. Django verarbeitet die Klassenattribute direkt.
    Rueckgabewert:
    Kein direkter Rueckgabewert. Die Klasse liefert Migrationsoperationen.
    """

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_per_unit", models.FloatField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_boms",
                        to="operations.product",
                    ),
                ),
                (
                    "finished_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="operations.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("finished_product", "component")},
            },
        ),
    ]
