"""
Dateirolle:
Diese Migration passt das Datenbankschema fuer die Mengenangabe in
Stuecklistenpositionen an.
Generated by Django 6.0.3 on 2026-03-10 23:06
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Zweck:
    Beschreibt die Aenderung des Feldtyps `quantity_per_unit` im Modell `BillOfMaterialItem`.
    Parameter:
    Keine Methodenparameter. Django wertet nur die Klassenattribute aus.
    Rueckgabewert:
    Kein direkter Rueckgabewert. Die Klasse definiert eine Feldaenderung fuer das Schema.
    """

    dependencies = [
        ("operations", "0002_billofmaterialitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterialitem",
            name="quantity_per_unit",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
