"""
Dateirolle:
Diese Migration fuehrt Validatoren und Default-Werte fuer Mengenfelder ein
und aktualisiert damit mehrere Modelle gleichzeitig.
Generated by Django 6.0.3 on 2026-03-10 23:50
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Zweck:
    Beschreibt mehrere Feldanpassungen fuer Mengenvalidierung in Stueckliste,
    Lieferungen, Lagerbestand und Produktionsauftraegen.
    Parameter:
    Keine Methodenparameter. Django interpretiert die Klassenattribute direkt.
    Rueckgabewert:
    Kein direkter Rueckgabewert. Die Klasse liefert die Schemaaenderungen.
    """

    dependencies = [
        ("operations", "0003_alter_billofmaterialitem_quantity_per_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterialitem",
            name="quantity_per_unit",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
