"""
Dateirolle:
Diese Migration verfeinert die Mengenfelder von Lieferungen und
Produktionsauftraegen weiter durch Validierungsanpassungen.
Generated by Django 6.0.3 on 2026-03-11 00:04
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Zweck:
    Beschreibt Feldanpassungen fuer Mengenvalidierung bei Lieferungen und Auftraegen.
    Parameter:
    Keine Methodenparameter. Django liest nur die Migrationsattribute.
    Rueckgabewert:
    Kein direkter Rueckgabewert. Die Klasse definiert Schemaoperationen.
    """

    dependencies = [
        ("operations", "0004_alter_billofmaterialitem_quantity_per_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
