"""
Dateirolle:
Diese Migration erweitert das Produktmodell um Sicherheitsbestand und Meldebestand,
damit Bestandswarnungen fachlich sauber berechnet werden koennen.
Generated by Django 6.0.3 on 2026-03-12 18:19
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Zweck:
    Beschreibt die Schemaerweiterung des Produktmodells um die Felder
    `reorder_point` und `safety_stock`.
    Parameter:
    Keine Methodenparameter. Django verarbeitet die Migrationsattribute direkt.
    Rueckgabewert:
    Kein direkter Rueckgabewert. Die Klasse definiert die Datenbankschema-Aenderung.
    """

    dependencies = [
        ('operations', '0005_alter_delivery_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
